# postgresql_settings: &postgresql_settings
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: postgres
#   password: ENV["DB_PASSWORD"]
#   host: 130.211.130.40
#   database: clustr

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  # url: <%= ENV['DATABASE_URL'] %>
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
